dist: trusty
sudo: true

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
      
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

env:
  global:
    - OPENS3D_SOURCE=${TRAVIS_BUILD_DIR}/src
    - OPENS3D_BUILD=${TRAVIS_BUILD_DIR}/src/build
    
#before_install:
#  - sudo apt-get -qq update
  
#install:
#  - export CXX=$COMPILER
#  - sudo apt-get install -y libopencv-dev
    
before_script:
  # Display cmake version
  - cmake --version
  # Create build folder
  - mkdir $OPENS3D_BUILD && cd $OPENS3D_BUILD
  - cmake .. -DOpenS3D_BUILD_APPS=OFF -DOpenS3D_USE_CUDA=OFF

script: 
- make -j2 && make test
